### ISSUE TITLE
Is LogisticPCA the same as this repo?

### ISSUE THREAD

**Issue by BradKML** [brudfors/logistic-PCA-Tipping#1]
There is a new repo that came out with a similar name but different graph, are they similar? https://github.com/andland/logisticPCA

**Comment by brudfors** [comment]
Hi @BrandonKMLee, It looks to me as if the repo you point to (https://github.com/andland/logisticPCA) is a different formulation of logistic PCA to the one implemented in this repo. If you look at the preprint that code is based on (https://arxiv.org/pdf/1510.06112.pdf), you can see they mention Tipping's method (implemented here) and how it differs from their proposed formulation (last paragraph of the Background section).
